# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
<<<<<<<< HEAD:.circleci/ci-web3-gamefi.yml
           # visit app.circleci.com/settings/project/github/Dargon789/foundry/environment-variables
========
          # visit app.circleci.com/settings/project/github/Dargon789/foundry/environment-variables
>>>>>>>> tea/custom-unmounted-button:.circleci/ci-foundry.yml
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  web3-defi-game-project:

    executor: my-custom-executor
    steps:
      - checkout
      - run: echo "Build started"

workflows:
  my-custom-workflow:
    jobs:
      - web3-defi-game-project
